### ISSUE TITLE
How to add other elements to the overlay?

### ISSUE THREAD

**Issue by zhouhao27** [miketricking/miketricking.github.io#1]
Great effect. But what if I want to add more elements such as **p** , **span**,  **img** to overlay, what should I do? Thanks

**Comment by miketricking** [comment]
Depends on what you are trying to achieve to be honest along with the effect you are using. You can add any elements as you wish as per normal HTML. It just depends on if you want them to act the same as the P or IMG elements that are already provided and styled. If that is the case then you can simply at the element to all the same styles as P/IMG
