### ISSUE TITLE
Effect 3, 6 and 13 do not properly work on IE

### ISSUE THREAD

**Issue by drbeat** [miketricking/miketricking.github.io#10]
Hi,

I love your work and use it regularly.

Latetly I noticed that the effects 3, 6 and 13 do not work on IE as IE does not know how to interpret "filter:".

Do you have an idea for a workaround?

Thanks

**Comment by miketricking** [comment]
For 'filter:' try '-ms-filter:'

Let me know 👍

**Comment by drbeat** [comment]
Sadly -ms-filter does not work on IE 11 and up. :(

**Comment by miketricking** [comment]
Ah sorry, the css filter is not supported on any version of IE unfortunately. Rather than using the filter: brightness you can try this solution instead: 

http://stackoverflow.com/questions/23276405/crossbrowser-brightness-filter-over-img-using-css
