### ISSUE TITLE
Not working on ipad/mobile devices

### ISSUE THREAD

**Issue by Kittybiccy** [miketricking/miketricking.github.io#4]
Hi Mike,

I've got the blocks working really nicely on my site. Only thing is, when it's on an ipad/mobile device, it's not working. When you view your examples on the ipad and you click on one of the blocks, the whole panel with the code pops up but on my test pages, nothing happens (as in, no hover effect and then <p> displayed to allow for clicking) . Have you included a bit of jquery or some additional code to get these to work on mobile devices or any idea how I can make the box itself the trigger/link as when I've played around and tried to do this so far, it knocks everything out.

Any ideas or suggestions greatly received, thank you!

**Comment by martmwangi** [comment]
Did you find a solution for this especially for the ipad?

**Comment by miketricking** [comment]
I have added some comments about mobile/touch devices to the read me. These generally aren't supported well on touch devices. It all depends on the device in question and how it handles :hover states. See comments below/view the read me for some more info on this.


We need to consider mobile, the hovers that reveal social icons are great except for many these will be inaccessible as some mobiles do not understand a hover state. One way would be to put some visible social icons else where and leave the hover social icons there as a nice effect for those who find them. Another option is to use CSS media queries so on small screen sizes the styles are already in place. They will not be able to see the cool effect but at lest you are making any content hidden by the hover styles more accessible.

For example on the first effect these are the styles that are applied during a :hover state. So you'd simply copy the styles again and wrap them inside and media query and remove the :hover part of it.
