### ISSUE TITLE
Hover Effect 10

### ISSUE THREAD

**Issue by CydGoblin** [miketricking/miketricking.github.io#5]
After closing the modal for Hover Effect 10 this happens until reload:
![hover](https://cloud.githubusercontent.com/assets/4932347/15543424/173430c8-2252-11e6-8cbf-e09d377a9e85.gif)

**Comment by ka-er-zet** [comment]
Try to add "visibility: hidden" at .hovereffect .overlay class and "visibility: visible" at .hovereffect:hover .overlay,
.hovereffect:hover h2,
.hovereffect:hover p.icon-links a {
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
}

**Comment by miketricking** [comment]
Thanks @svistakk fix is now in place
