### ISSUE TITLE
clashing with .affix nav in BS3

### ISSUE THREAD

**Issue by Cytex01** [miketricking/miketricking.github.io#6]
Hi Mike,

First of all, I love your code. This is the most elegant and beautiful solution I could find.
However I ran into something strange. I'm using a navigation bar with the "affix" class in BootStrap. So my navbar is just a simple default navbar, except when you scroll it sticks to the top.
I want to use effect 12. So here is the situation.
When the navbar is static, so not in "sticky"-mode, I see no problem. When I scroll and the navbar goes into "sticky"-mode (no longer static) there appears a 1px border along the bottom of image (same color I use for .hovereffect).
Also when I scroll back to the top (navbar becomes static again) the border goed away.
Could you look into this please?

**Comment by miketricking** [comment]
Sorry for the very late reply did you ever get this resolved?
