### ISSUE TITLE
Hover anchor tag is not working (CSS3 Issue)

### ISSUE THREAD

**Issue by dham-tharan** [miketricking/miketricking.github.io#7]
When am hovering the image the anchor tag is not working because of the #css3, in yours you missed the -moz browser compatibility coding. If you fix it users will get fulfill from yours hover things.

**Comment by miketricking** [comment]
I used autoprefixer for these. It would have generate a -moz prefix if one was needed. What version of firefox are you using and what was css style do you believe the -moz prefix is missing from?

**Comment by dham-tharan** [comment]
I know that you are used autoprefixer. Am using firefox 51.0.1, but particularly the links are not working in firefox. After when am initiated -moz code in my style then only it works properly. Apart from this particular one, everything working good in all browsers. 

Here is my code:

.view-overlay-pro img {
    transform: scaleY(1);
    transition: all .7s ease-in-out 0s;
    -moz-transform: scaleY(1);
    -moz-transition: all .7s ease-in-out 0s;
    -webkit-transform: scaleY(1);
    -webkit-transition: all .7s ease-in-out 0s
}
.view-overlay-pro:hover img {
    opacity: 0;
    transform: scale(10);
    -moz-transform: scale(10);
    -webkit-transform: scale(10)
}
